// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/code-reviewer/watcher/github/pkg"
	"github.com/bborbe/time"
)

type GitHubClient struct {
	GetPRDetailsStub        func(context.Context, string, string, int) (pkg.PRDetails, error)
	getPRDetailsMutex       sync.RWMutex
	getPRDetailsArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
	}
	getPRDetailsReturns struct {
		result1 pkg.PRDetails
		result2 error
	}
	getPRDetailsReturnsOnCall map[int]struct {
		result1 pkg.PRDetails
		result2 error
	}
	SearchPRsStub        func(context.Context, string, time.DateTime, int) (pkg.SearchResult, error)
	searchPRsMutex       sync.RWMutex
	searchPRsArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 time.DateTime
		arg4 int
	}
	searchPRsReturns struct {
		result1 pkg.SearchResult
		result2 error
	}
	searchPRsReturnsOnCall map[int]struct {
		result1 pkg.SearchResult
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *GitHubClient) GetPRDetails(arg1 context.Context, arg2 string, arg3 string, arg4 int) (pkg.PRDetails, error) {
	fake.getPRDetailsMutex.Lock()
	ret, specificReturn := fake.getPRDetailsReturnsOnCall[len(fake.getPRDetailsArgsForCall)]
	fake.getPRDetailsArgsForCall = append(fake.getPRDetailsArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.GetPRDetailsStub
	fakeReturns := fake.getPRDetailsReturns
	fake.recordInvocation("GetPRDetails", []interface{}{arg1, arg2, arg3, arg4})
	fake.getPRDetailsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitHubClient) GetPRDetailsCallCount() int {
	fake.getPRDetailsMutex.RLock()
	defer fake.getPRDetailsMutex.RUnlock()
	return len(fake.getPRDetailsArgsForCall)
}

func (fake *GitHubClient) GetPRDetailsCalls(stub func(context.Context, string, string, int) (pkg.PRDetails, error)) {
	fake.getPRDetailsMutex.Lock()
	defer fake.getPRDetailsMutex.Unlock()
	fake.GetPRDetailsStub = stub
}

func (fake *GitHubClient) GetPRDetailsArgsForCall(i int) (context.Context, string, string, int) {
	fake.getPRDetailsMutex.RLock()
	defer fake.getPRDetailsMutex.RUnlock()
	argsForCall := fake.getPRDetailsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *GitHubClient) GetPRDetailsReturns(result1 pkg.PRDetails, result2 error) {
	fake.getPRDetailsMutex.Lock()
	defer fake.getPRDetailsMutex.Unlock()
	fake.GetPRDetailsStub = nil
	fake.getPRDetailsReturns = struct {
		result1 pkg.PRDetails
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) GetPRDetailsReturnsOnCall(i int, result1 pkg.PRDetails, result2 error) {
	fake.getPRDetailsMutex.Lock()
	defer fake.getPRDetailsMutex.Unlock()
	fake.GetPRDetailsStub = nil
	if fake.getPRDetailsReturnsOnCall == nil {
		fake.getPRDetailsReturnsOnCall = make(map[int]struct {
			result1 pkg.PRDetails
			result2 error
		})
	}
	fake.getPRDetailsReturnsOnCall[i] = struct {
		result1 pkg.PRDetails
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) SearchPRs(arg1 context.Context, arg2 string, arg3 time.DateTime, arg4 int) (pkg.SearchResult, error) {
	fake.searchPRsMutex.Lock()
	ret, specificReturn := fake.searchPRsReturnsOnCall[len(fake.searchPRsArgsForCall)]
	fake.searchPRsArgsForCall = append(fake.searchPRsArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 time.DateTime
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.SearchPRsStub
	fakeReturns := fake.searchPRsReturns
	fake.recordInvocation("SearchPRs", []interface{}{arg1, arg2, arg3, arg4})
	fake.searchPRsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitHubClient) SearchPRsCallCount() int {
	fake.searchPRsMutex.RLock()
	defer fake.searchPRsMutex.RUnlock()
	return len(fake.searchPRsArgsForCall)
}

func (fake *GitHubClient) SearchPRsCalls(stub func(context.Context, string, time.DateTime, int) (pkg.SearchResult, error)) {
	fake.searchPRsMutex.Lock()
	defer fake.searchPRsMutex.Unlock()
	fake.SearchPRsStub = stub
}

func (fake *GitHubClient) SearchPRsArgsForCall(i int) (context.Context, string, time.DateTime, int) {
	fake.searchPRsMutex.RLock()
	defer fake.searchPRsMutex.RUnlock()
	argsForCall := fake.searchPRsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *GitHubClient) SearchPRsReturns(result1 pkg.SearchResult, result2 error) {
	fake.searchPRsMutex.Lock()
	defer fake.searchPRsMutex.Unlock()
	fake.SearchPRsStub = nil
	fake.searchPRsReturns = struct {
		result1 pkg.SearchResult
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) SearchPRsReturnsOnCall(i int, result1 pkg.SearchResult, result2 error) {
	fake.searchPRsMutex.Lock()
	defer fake.searchPRsMutex.Unlock()
	fake.SearchPRsStub = nil
	if fake.searchPRsReturnsOnCall == nil {
		fake.searchPRsReturnsOnCall = make(map[int]struct {
			result1 pkg.SearchResult
			result2 error
		})
	}
	fake.searchPRsReturnsOnCall[i] = struct {
		result1 pkg.SearchResult
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *GitHubClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.GitHubClient = new(GitHubClient)
