apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: maintainer-watcher-github-build
  namespace: '{{ "NAMESPACE" | env }}'
data:
  PEM_KEY: '{{ "WATCHER_GITHUB_BUILD_PEM_KEY" | env | teamvaultFileBase64 }}'
