// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/maintainer/agent/pr-reviewer/pkg"
	"github.com/bborbe/maintainer/lib/prurl"
)

type PrPoster struct {
	PostStub        func(context.Context, pkg.PostRequest) pkg.PostResult
	postMutex       sync.RWMutex
	postArgsForCall []struct {
		arg1 context.Context
		arg2 pkg.PostRequest
	}
	postReturns struct {
		result1 pkg.PostResult
	}
	postReturnsOnCall map[int]struct {
		result1 pkg.PostResult
	}
	PostLGTMStub        func(context.Context, prurl.PRInfo, string, string, string) pkg.PostResult
	postLGTMMutex       sync.RWMutex
	postLGTMArgsForCall []struct {
		arg1 context.Context
		arg2 prurl.PRInfo
		arg3 string
		arg4 string
		arg5 string
	}
	postLGTMReturns struct {
		result1 pkg.PostResult
	}
	postLGTMReturnsOnCall map[int]struct {
		result1 pkg.PostResult
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *PrPoster) Post(arg1 context.Context, arg2 pkg.PostRequest) pkg.PostResult {
	fake.postMutex.Lock()
	ret, specificReturn := fake.postReturnsOnCall[len(fake.postArgsForCall)]
	fake.postArgsForCall = append(fake.postArgsForCall, struct {
		arg1 context.Context
		arg2 pkg.PostRequest
	}{arg1, arg2})
	stub := fake.PostStub
	fakeReturns := fake.postReturns
	fake.recordInvocation("Post", []interface{}{arg1, arg2})
	fake.postMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *PrPoster) PostCallCount() int {
	fake.postMutex.RLock()
	defer fake.postMutex.RUnlock()
	return len(fake.postArgsForCall)
}

func (fake *PrPoster) PostCalls(stub func(context.Context, pkg.PostRequest) pkg.PostResult) {
	fake.postMutex.Lock()
	defer fake.postMutex.Unlock()
	fake.PostStub = stub
}

func (fake *PrPoster) PostArgsForCall(i int) (context.Context, pkg.PostRequest) {
	fake.postMutex.RLock()
	defer fake.postMutex.RUnlock()
	argsForCall := fake.postArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *PrPoster) PostReturns(result1 pkg.PostResult) {
	fake.postMutex.Lock()
	defer fake.postMutex.Unlock()
	fake.PostStub = nil
	fake.postReturns = struct {
		result1 pkg.PostResult
	}{result1}
}

func (fake *PrPoster) PostReturnsOnCall(i int, result1 pkg.PostResult) {
	fake.postMutex.Lock()
	defer fake.postMutex.Unlock()
	fake.PostStub = nil
	if fake.postReturnsOnCall == nil {
		fake.postReturnsOnCall = make(map[int]struct {
			result1 pkg.PostResult
		})
	}
	fake.postReturnsOnCall[i] = struct {
		result1 pkg.PostResult
	}{result1}
}

func (fake *PrPoster) PostLGTM(arg1 context.Context, arg2 prurl.PRInfo, arg3 string, arg4 string, arg5 string) pkg.PostResult {
	fake.postLGTMMutex.Lock()
	ret, specificReturn := fake.postLGTMReturnsOnCall[len(fake.postLGTMArgsForCall)]
	fake.postLGTMArgsForCall = append(fake.postLGTMArgsForCall, struct {
		arg1 context.Context
		arg2 prurl.PRInfo
		arg3 string
		arg4 string
		arg5 string
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.PostLGTMStub
	fakeReturns := fake.postLGTMReturns
	fake.recordInvocation("PostLGTM", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.postLGTMMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *PrPoster) PostLGTMCallCount() int {
	fake.postLGTMMutex.RLock()
	defer fake.postLGTMMutex.RUnlock()
	return len(fake.postLGTMArgsForCall)
}

func (fake *PrPoster) PostLGTMCalls(stub func(context.Context, prurl.PRInfo, string, string, string) pkg.PostResult) {
	fake.postLGTMMutex.Lock()
	defer fake.postLGTMMutex.Unlock()
	fake.PostLGTMStub = stub
}

func (fake *PrPoster) PostLGTMArgsForCall(i int) (context.Context, prurl.PRInfo, string, string, string) {
	fake.postLGTMMutex.RLock()
	defer fake.postLGTMMutex.RUnlock()
	argsForCall := fake.postLGTMArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *PrPoster) PostLGTMReturns(result1 pkg.PostResult) {
	fake.postLGTMMutex.Lock()
	defer fake.postLGTMMutex.Unlock()
	fake.PostLGTMStub = nil
	fake.postLGTMReturns = struct {
		result1 pkg.PostResult
	}{result1}
}

func (fake *PrPoster) PostLGTMReturnsOnCall(i int, result1 pkg.PostResult) {
	fake.postLGTMMutex.Lock()
	defer fake.postLGTMMutex.Unlock()
	fake.PostLGTMStub = nil
	if fake.postLGTMReturnsOnCall == nil {
		fake.postLGTMReturnsOnCall = make(map[int]struct {
			result1 pkg.PostResult
		})
	}
	fake.postLGTMReturnsOnCall[i] = struct {
		result1 pkg.PostResult
	}{result1}
}

func (fake *PrPoster) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *PrPoster) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.PrPoster = new(PrPoster)
