// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/maintainer/agent/pr-reviewer/pkg/githubposter"
)

type PrPoster struct {
	PostStub        func(context.Context, githubposter.PostRequest) githubposter.PostResult
	postMutex       sync.RWMutex
	postArgsForCall []struct {
		arg1 context.Context
		arg2 githubposter.PostRequest
	}
	postReturns struct {
		result1 githubposter.PostResult
	}
	postReturnsOnCall map[int]struct {
		result1 githubposter.PostResult
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *PrPoster) Post(arg1 context.Context, arg2 githubposter.PostRequest) githubposter.PostResult {
	fake.postMutex.Lock()
	ret, specificReturn := fake.postReturnsOnCall[len(fake.postArgsForCall)]
	fake.postArgsForCall = append(fake.postArgsForCall, struct {
		arg1 context.Context
		arg2 githubposter.PostRequest
	}{arg1, arg2})
	stub := fake.PostStub
	fakeReturns := fake.postReturns
	fake.recordInvocation("Post", []interface{}{arg1, arg2})
	fake.postMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *PrPoster) PostCallCount() int {
	fake.postMutex.RLock()
	defer fake.postMutex.RUnlock()
	return len(fake.postArgsForCall)
}

func (fake *PrPoster) PostCalls(stub func(context.Context, githubposter.PostRequest) githubposter.PostResult) {
	fake.postMutex.Lock()
	defer fake.postMutex.Unlock()
	fake.PostStub = stub
}

func (fake *PrPoster) PostArgsForCall(i int) (context.Context, githubposter.PostRequest) {
	fake.postMutex.RLock()
	defer fake.postMutex.RUnlock()
	argsForCall := fake.postArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *PrPoster) PostReturns(result1 githubposter.PostResult) {
	fake.postMutex.Lock()
	defer fake.postMutex.Unlock()
	fake.PostStub = nil
	fake.postReturns = struct {
		result1 githubposter.PostResult
	}{result1}
}

func (fake *PrPoster) PostReturnsOnCall(i int, result1 githubposter.PostResult) {
	fake.postMutex.Lock()
	defer fake.postMutex.Unlock()
	fake.PostStub = nil
	if fake.postReturnsOnCall == nil {
		fake.postReturnsOnCall = make(map[int]struct {
			result1 githubposter.PostResult
		})
	}
	fake.postReturnsOnCall[i] = struct {
		result1 githubposter.PostResult
	}{result1}
}

func (fake *PrPoster) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *PrPoster) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ githubposter.PrPoster = new(PrPoster)
