// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/maintainer/agent/pr-reviewer/pkg/git"
)

type RepoManager struct {
	EnsureBareCloneStub        func(context.Context, string) (string, error)
	ensureBareCloneMutex       sync.RWMutex
	ensureBareCloneArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	ensureBareCloneReturns struct {
		result1 string
		result2 error
	}
	ensureBareCloneReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	EnsureWorktreeStub        func(context.Context, string, string, string) (string, error)
	ensureWorktreeMutex       sync.RWMutex
	ensureWorktreeArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	ensureWorktreeReturns struct {
		result1 string
		result2 error
	}
	ensureWorktreeReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	PruneAllWorktreesStub        func(context.Context) error
	pruneAllWorktreesMutex       sync.RWMutex
	pruneAllWorktreesArgsForCall []struct {
		arg1 context.Context
	}
	pruneAllWorktreesReturns struct {
		result1 error
	}
	pruneAllWorktreesReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *RepoManager) EnsureBareClone(arg1 context.Context, arg2 string) (string, error) {
	fake.ensureBareCloneMutex.Lock()
	ret, specificReturn := fake.ensureBareCloneReturnsOnCall[len(fake.ensureBareCloneArgsForCall)]
	fake.ensureBareCloneArgsForCall = append(fake.ensureBareCloneArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.EnsureBareCloneStub
	fakeReturns := fake.ensureBareCloneReturns
	fake.recordInvocation("EnsureBareClone", []interface{}{arg1, arg2})
	fake.ensureBareCloneMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *RepoManager) EnsureBareCloneCallCount() int {
	fake.ensureBareCloneMutex.RLock()
	defer fake.ensureBareCloneMutex.RUnlock()
	return len(fake.ensureBareCloneArgsForCall)
}

func (fake *RepoManager) EnsureBareCloneCalls(stub func(context.Context, string) (string, error)) {
	fake.ensureBareCloneMutex.Lock()
	defer fake.ensureBareCloneMutex.Unlock()
	fake.EnsureBareCloneStub = stub
}

func (fake *RepoManager) EnsureBareCloneArgsForCall(i int) (context.Context, string) {
	fake.ensureBareCloneMutex.RLock()
	defer fake.ensureBareCloneMutex.RUnlock()
	argsForCall := fake.ensureBareCloneArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *RepoManager) EnsureBareCloneReturns(result1 string, result2 error) {
	fake.ensureBareCloneMutex.Lock()
	defer fake.ensureBareCloneMutex.Unlock()
	fake.EnsureBareCloneStub = nil
	fake.ensureBareCloneReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *RepoManager) EnsureBareCloneReturnsOnCall(i int, result1 string, result2 error) {
	fake.ensureBareCloneMutex.Lock()
	defer fake.ensureBareCloneMutex.Unlock()
	fake.EnsureBareCloneStub = nil
	if fake.ensureBareCloneReturnsOnCall == nil {
		fake.ensureBareCloneReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.ensureBareCloneReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *RepoManager) EnsureWorktree(arg1 context.Context, arg2 string, arg3 string, arg4 string) (string, error) {
	fake.ensureWorktreeMutex.Lock()
	ret, specificReturn := fake.ensureWorktreeReturnsOnCall[len(fake.ensureWorktreeArgsForCall)]
	fake.ensureWorktreeArgsForCall = append(fake.ensureWorktreeArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.EnsureWorktreeStub
	fakeReturns := fake.ensureWorktreeReturns
	fake.recordInvocation("EnsureWorktree", []interface{}{arg1, arg2, arg3, arg4})
	fake.ensureWorktreeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *RepoManager) EnsureWorktreeCallCount() int {
	fake.ensureWorktreeMutex.RLock()
	defer fake.ensureWorktreeMutex.RUnlock()
	return len(fake.ensureWorktreeArgsForCall)
}

func (fake *RepoManager) EnsureWorktreeCalls(stub func(context.Context, string, string, string) (string, error)) {
	fake.ensureWorktreeMutex.Lock()
	defer fake.ensureWorktreeMutex.Unlock()
	fake.EnsureWorktreeStub = stub
}

func (fake *RepoManager) EnsureWorktreeArgsForCall(i int) (context.Context, string, string, string) {
	fake.ensureWorktreeMutex.RLock()
	defer fake.ensureWorktreeMutex.RUnlock()
	argsForCall := fake.ensureWorktreeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *RepoManager) EnsureWorktreeReturns(result1 string, result2 error) {
	fake.ensureWorktreeMutex.Lock()
	defer fake.ensureWorktreeMutex.Unlock()
	fake.EnsureWorktreeStub = nil
	fake.ensureWorktreeReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *RepoManager) EnsureWorktreeReturnsOnCall(i int, result1 string, result2 error) {
	fake.ensureWorktreeMutex.Lock()
	defer fake.ensureWorktreeMutex.Unlock()
	fake.EnsureWorktreeStub = nil
	if fake.ensureWorktreeReturnsOnCall == nil {
		fake.ensureWorktreeReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.ensureWorktreeReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *RepoManager) PruneAllWorktrees(arg1 context.Context) error {
	fake.pruneAllWorktreesMutex.Lock()
	ret, specificReturn := fake.pruneAllWorktreesReturnsOnCall[len(fake.pruneAllWorktreesArgsForCall)]
	fake.pruneAllWorktreesArgsForCall = append(fake.pruneAllWorktreesArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.PruneAllWorktreesStub
	fakeReturns := fake.pruneAllWorktreesReturns
	fake.recordInvocation("PruneAllWorktrees", []interface{}{arg1})
	fake.pruneAllWorktreesMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *RepoManager) PruneAllWorktreesCallCount() int {
	fake.pruneAllWorktreesMutex.RLock()
	defer fake.pruneAllWorktreesMutex.RUnlock()
	return len(fake.pruneAllWorktreesArgsForCall)
}

func (fake *RepoManager) PruneAllWorktreesCalls(stub func(context.Context) error) {
	fake.pruneAllWorktreesMutex.Lock()
	defer fake.pruneAllWorktreesMutex.Unlock()
	fake.PruneAllWorktreesStub = stub
}

func (fake *RepoManager) PruneAllWorktreesArgsForCall(i int) context.Context {
	fake.pruneAllWorktreesMutex.RLock()
	defer fake.pruneAllWorktreesMutex.RUnlock()
	argsForCall := fake.pruneAllWorktreesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *RepoManager) PruneAllWorktreesReturns(result1 error) {
	fake.pruneAllWorktreesMutex.Lock()
	defer fake.pruneAllWorktreesMutex.Unlock()
	fake.PruneAllWorktreesStub = nil
	fake.pruneAllWorktreesReturns = struct {
		result1 error
	}{result1}
}

func (fake *RepoManager) PruneAllWorktreesReturnsOnCall(i int, result1 error) {
	fake.pruneAllWorktreesMutex.Lock()
	defer fake.pruneAllWorktreesMutex.Unlock()
	fake.PruneAllWorktreesStub = nil
	if fake.pruneAllWorktreesReturnsOnCall == nil {
		fake.pruneAllWorktreesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.pruneAllWorktreesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *RepoManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *RepoManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ git.RepoManager = new(RepoManager)
