// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/maintainer/agent/pr-reviewer/pkg/githubposter"
)

type ReviewVerifier struct {
	VerifyReviewStub        func(context.Context, githubposter.VerifyRequest) githubposter.VerifyResult
	verifyReviewMutex       sync.RWMutex
	verifyReviewArgsForCall []struct {
		arg1 context.Context
		arg2 githubposter.VerifyRequest
	}
	verifyReviewReturns struct {
		result1 githubposter.VerifyResult
	}
	verifyReviewReturnsOnCall map[int]struct {
		result1 githubposter.VerifyResult
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ReviewVerifier) VerifyReview(arg1 context.Context, arg2 githubposter.VerifyRequest) githubposter.VerifyResult {
	fake.verifyReviewMutex.Lock()
	ret, specificReturn := fake.verifyReviewReturnsOnCall[len(fake.verifyReviewArgsForCall)]
	fake.verifyReviewArgsForCall = append(fake.verifyReviewArgsForCall, struct {
		arg1 context.Context
		arg2 githubposter.VerifyRequest
	}{arg1, arg2})
	stub := fake.VerifyReviewStub
	fakeReturns := fake.verifyReviewReturns
	fake.recordInvocation("VerifyReview", []interface{}{arg1, arg2})
	fake.verifyReviewMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ReviewVerifier) VerifyReviewCallCount() int {
	fake.verifyReviewMutex.RLock()
	defer fake.verifyReviewMutex.RUnlock()
	return len(fake.verifyReviewArgsForCall)
}

func (fake *ReviewVerifier) VerifyReviewCalls(stub func(context.Context, githubposter.VerifyRequest) githubposter.VerifyResult) {
	fake.verifyReviewMutex.Lock()
	defer fake.verifyReviewMutex.Unlock()
	fake.VerifyReviewStub = stub
}

func (fake *ReviewVerifier) VerifyReviewArgsForCall(i int) (context.Context, githubposter.VerifyRequest) {
	fake.verifyReviewMutex.RLock()
	defer fake.verifyReviewMutex.RUnlock()
	argsForCall := fake.verifyReviewArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ReviewVerifier) VerifyReviewReturns(result1 githubposter.VerifyResult) {
	fake.verifyReviewMutex.Lock()
	defer fake.verifyReviewMutex.Unlock()
	fake.VerifyReviewStub = nil
	fake.verifyReviewReturns = struct {
		result1 githubposter.VerifyResult
	}{result1}
}

func (fake *ReviewVerifier) VerifyReviewReturnsOnCall(i int, result1 githubposter.VerifyResult) {
	fake.verifyReviewMutex.Lock()
	defer fake.verifyReviewMutex.Unlock()
	fake.VerifyReviewStub = nil
	if fake.verifyReviewReturnsOnCall == nil {
		fake.verifyReviewReturnsOnCall = make(map[int]struct {
			result1 githubposter.VerifyResult
		})
	}
	fake.verifyReviewReturnsOnCall[i] = struct {
		result1 githubposter.VerifyResult
	}{result1}
}

func (fake *ReviewVerifier) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ReviewVerifier) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ githubposter.ReviewVerifier = new(ReviewVerifier)
