// Code generated by counterfeiter. DO NOT EDIT.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/maintainer/agent/github-releaser/pkg/git"
)

type GitOps struct {
	CloneStub        func(context.Context, string, string, string) error
	cloneMutex       sync.RWMutex
	cloneArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	cloneReturns struct {
		result1 error
	}
	cloneReturnsOnCall map[int]struct {
		result1 error
	}
	CommitStub        func(context.Context, string, string, ...string) (string, error)
	commitMutex       sync.RWMutex
	commitArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 []string
	}
	commitReturns struct {
		result1 string
		result2 error
	}
	commitReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	CommittedFilesStub        func(context.Context, string) ([]string, error)
	committedFilesMutex       sync.RWMutex
	committedFilesArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	committedFilesReturns struct {
		result1 []string
		result2 error
	}
	committedFilesReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	LsRemoteStub        func(context.Context, string, string, string) (string, error)
	lsRemoteMutex       sync.RWMutex
	lsRemoteArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	lsRemoteReturns struct {
		result1 string
		result2 error
	}
	lsRemoteReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	PushStub        func(context.Context, string, ...string) error
	pushMutex       sync.RWMutex
	pushArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 []string
	}
	pushReturns struct {
		result1 error
	}
	pushReturnsOnCall map[int]struct {
		result1 error
	}
	TagStub        func(context.Context, string, string, string) error
	tagMutex       sync.RWMutex
	tagArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	tagReturns struct {
		result1 error
	}
	tagReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *GitOps) Clone(arg1 context.Context, arg2 string, arg3 string, arg4 string) error {
	fake.cloneMutex.Lock()
	ret, specificReturn := fake.cloneReturnsOnCall[len(fake.cloneArgsForCall)]
	fake.cloneArgsForCall = append(fake.cloneArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.CloneStub
	fakeReturns := fake.cloneReturns
	fake.recordInvocation("Clone", []interface{}{arg1, arg2, arg3, arg4})
	fake.cloneMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *GitOps) CloneCallCount() int {
	fake.cloneMutex.RLock()
	defer fake.cloneMutex.RUnlock()
	return len(fake.cloneArgsForCall)
}

func (fake *GitOps) CloneCalls(stub func(context.Context, string, string, string) error) {
	fake.cloneMutex.Lock()
	defer fake.cloneMutex.Unlock()
	fake.CloneStub = stub
}

func (fake *GitOps) CloneArgsForCall(i int) (context.Context, string, string, string) {
	fake.cloneMutex.RLock()
	defer fake.cloneMutex.RUnlock()
	argsForCall := fake.cloneArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *GitOps) CloneReturns(result1 error) {
	fake.cloneMutex.Lock()
	defer fake.cloneMutex.Unlock()
	fake.CloneStub = nil
	fake.cloneReturns = struct {
		result1 error
	}{result1}
}

func (fake *GitOps) CloneReturnsOnCall(i int, result1 error) {
	fake.cloneMutex.Lock()
	defer fake.cloneMutex.Unlock()
	fake.CloneStub = nil
	if fake.cloneReturnsOnCall == nil {
		fake.cloneReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.cloneReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *GitOps) Commit(arg1 context.Context, arg2 string, arg3 string, arg4 ...string) (string, error) {
	fake.commitMutex.Lock()
	ret, specificReturn := fake.commitReturnsOnCall[len(fake.commitArgsForCall)]
	fake.commitArgsForCall = append(fake.commitArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 []string
	}{arg1, arg2, arg3, arg4})
	stub := fake.CommitStub
	fakeReturns := fake.commitReturns
	fake.recordInvocation("Commit", []interface{}{arg1, arg2, arg3, arg4})
	fake.commitMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitOps) CommitCallCount() int {
	fake.commitMutex.RLock()
	defer fake.commitMutex.RUnlock()
	return len(fake.commitArgsForCall)
}

func (fake *GitOps) CommitCalls(stub func(context.Context, string, string, ...string) (string, error)) {
	fake.commitMutex.Lock()
	defer fake.commitMutex.Unlock()
	fake.CommitStub = stub
}

func (fake *GitOps) CommitArgsForCall(i int) (context.Context, string, string, []string) {
	fake.commitMutex.RLock()
	defer fake.commitMutex.RUnlock()
	argsForCall := fake.commitArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *GitOps) CommitReturns(result1 string, result2 error) {
	fake.commitMutex.Lock()
	defer fake.commitMutex.Unlock()
	fake.CommitStub = nil
	fake.commitReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *GitOps) CommitReturnsOnCall(i int, result1 string, result2 error) {
	fake.commitMutex.Lock()
	defer fake.commitMutex.Unlock()
	fake.CommitStub = nil
	if fake.commitReturnsOnCall == nil {
		fake.commitReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.commitReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *GitOps) CommittedFiles(arg1 context.Context, arg2 string) ([]string, error) {
	fake.committedFilesMutex.Lock()
	ret, specificReturn := fake.committedFilesReturnsOnCall[len(fake.committedFilesArgsForCall)]
	fake.committedFilesArgsForCall = append(fake.committedFilesArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.CommittedFilesStub
	fakeReturns := fake.committedFilesReturns
	fake.recordInvocation("CommittedFiles", []interface{}{arg1, arg2})
	fake.committedFilesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitOps) CommittedFilesCallCount() int {
	fake.committedFilesMutex.RLock()
	defer fake.committedFilesMutex.RUnlock()
	return len(fake.committedFilesArgsForCall)
}

func (fake *GitOps) CommittedFilesCalls(stub func(context.Context, string) ([]string, error)) {
	fake.committedFilesMutex.Lock()
	defer fake.committedFilesMutex.Unlock()
	fake.CommittedFilesStub = stub
}

func (fake *GitOps) CommittedFilesArgsForCall(i int) (context.Context, string) {
	fake.committedFilesMutex.RLock()
	defer fake.committedFilesMutex.RUnlock()
	argsForCall := fake.committedFilesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *GitOps) CommittedFilesReturns(result1 []string, result2 error) {
	fake.committedFilesMutex.Lock()
	defer fake.committedFilesMutex.Unlock()
	fake.CommittedFilesStub = nil
	fake.committedFilesReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *GitOps) CommittedFilesReturnsOnCall(i int, result1 []string, result2 error) {
	fake.committedFilesMutex.Lock()
	defer fake.committedFilesMutex.Unlock()
	fake.CommittedFilesStub = nil
	if fake.committedFilesReturnsOnCall == nil {
		fake.committedFilesReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.committedFilesReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *GitOps) LsRemote(arg1 context.Context, arg2 string, arg3 string, arg4 string) (string, error) {
	fake.lsRemoteMutex.Lock()
	ret, specificReturn := fake.lsRemoteReturnsOnCall[len(fake.lsRemoteArgsForCall)]
	fake.lsRemoteArgsForCall = append(fake.lsRemoteArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.LsRemoteStub
	fakeReturns := fake.lsRemoteReturns
	fake.recordInvocation("LsRemote", []interface{}{arg1, arg2, arg3, arg4})
	fake.lsRemoteMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitOps) LsRemoteCallCount() int {
	fake.lsRemoteMutex.RLock()
	defer fake.lsRemoteMutex.RUnlock()
	return len(fake.lsRemoteArgsForCall)
}

func (fake *GitOps) LsRemoteCalls(stub func(context.Context, string, string, string) (string, error)) {
	fake.lsRemoteMutex.Lock()
	defer fake.lsRemoteMutex.Unlock()
	fake.LsRemoteStub = stub
}

func (fake *GitOps) LsRemoteArgsForCall(i int) (context.Context, string, string, string) {
	fake.lsRemoteMutex.RLock()
	defer fake.lsRemoteMutex.RUnlock()
	argsForCall := fake.lsRemoteArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *GitOps) LsRemoteReturns(result1 string, result2 error) {
	fake.lsRemoteMutex.Lock()
	defer fake.lsRemoteMutex.Unlock()
	fake.LsRemoteStub = nil
	fake.lsRemoteReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *GitOps) LsRemoteReturnsOnCall(i int, result1 string, result2 error) {
	fake.lsRemoteMutex.Lock()
	defer fake.lsRemoteMutex.Unlock()
	fake.LsRemoteStub = nil
	if fake.lsRemoteReturnsOnCall == nil {
		fake.lsRemoteReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.lsRemoteReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *GitOps) Push(arg1 context.Context, arg2 string, arg3 ...string) error {
	fake.pushMutex.Lock()
	ret, specificReturn := fake.pushReturnsOnCall[len(fake.pushArgsForCall)]
	fake.pushArgsForCall = append(fake.pushArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 []string
	}{arg1, arg2, arg3})
	stub := fake.PushStub
	fakeReturns := fake.pushReturns
	fake.recordInvocation("Push", []interface{}{arg1, arg2, arg3})
	fake.pushMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *GitOps) PushCallCount() int {
	fake.pushMutex.RLock()
	defer fake.pushMutex.RUnlock()
	return len(fake.pushArgsForCall)
}

func (fake *GitOps) PushCalls(stub func(context.Context, string, ...string) error) {
	fake.pushMutex.Lock()
	defer fake.pushMutex.Unlock()
	fake.PushStub = stub
}

func (fake *GitOps) PushArgsForCall(i int) (context.Context, string, []string) {
	fake.pushMutex.RLock()
	defer fake.pushMutex.RUnlock()
	argsForCall := fake.pushArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *GitOps) PushReturns(result1 error) {
	fake.pushMutex.Lock()
	defer fake.pushMutex.Unlock()
	fake.PushStub = nil
	fake.pushReturns = struct {
		result1 error
	}{result1}
}

func (fake *GitOps) PushReturnsOnCall(i int, result1 error) {
	fake.pushMutex.Lock()
	defer fake.pushMutex.Unlock()
	fake.PushStub = nil
	if fake.pushReturnsOnCall == nil {
		fake.pushReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.pushReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *GitOps) Tag(arg1 context.Context, arg2 string, arg3 string, arg4 string) error {
	fake.tagMutex.Lock()
	ret, specificReturn := fake.tagReturnsOnCall[len(fake.tagArgsForCall)]
	fake.tagArgsForCall = append(fake.tagArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.TagStub
	fakeReturns := fake.tagReturns
	fake.recordInvocation("Tag", []interface{}{arg1, arg2, arg3, arg4})
	fake.tagMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *GitOps) TagCallCount() int {
	fake.tagMutex.RLock()
	defer fake.tagMutex.RUnlock()
	return len(fake.tagArgsForCall)
}

func (fake *GitOps) TagCalls(stub func(context.Context, string, string, string) error) {
	fake.tagMutex.Lock()
	defer fake.tagMutex.Unlock()
	fake.TagStub = stub
}

func (fake *GitOps) TagArgsForCall(i int) (context.Context, string, string, string) {
	fake.tagMutex.RLock()
	defer fake.tagMutex.RUnlock()
	argsForCall := fake.tagArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *GitOps) TagReturns(result1 error) {
	fake.tagMutex.Lock()
	defer fake.tagMutex.Unlock()
	fake.TagStub = nil
	fake.tagReturns = struct {
		result1 error
	}{result1}
}

func (fake *GitOps) TagReturnsOnCall(i int, result1 error) {
	fake.tagMutex.Lock()
	defer fake.tagMutex.Unlock()
	fake.TagStub = nil
	if fake.tagReturnsOnCall == nil {
		fake.tagReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.tagReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *GitOps) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *GitOps) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ git.GitOps = new(GitOps)
