// Code generated by counterfeiter. DO NOT EDIT.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/maintainer/agent/github-releaser/pkg/githubreview"
)

type ReviewClient struct {
	FetchChangelogStub        func(context.Context, string, string) ([]byte, error)
	fetchChangelogMutex       sync.RWMutex
	fetchChangelogArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	fetchChangelogReturns struct {
		result1 []byte
		result2 error
	}
	fetchChangelogReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	ResolveTagCommitStub        func(context.Context, string, string, string) (string, error)
	resolveTagCommitMutex       sync.RWMutex
	resolveTagCommitArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	resolveTagCommitReturns struct {
		result1 string
		result2 error
	}
	resolveTagCommitReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	TagExistsStub        func(context.Context, string, string, string) (string, error)
	tagExistsMutex       sync.RWMutex
	tagExistsArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	tagExistsReturns struct {
		result1 string
		result2 error
	}
	tagExistsReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ReviewClient) FetchChangelog(arg1 context.Context, arg2 string, arg3 string) ([]byte, error) {
	fake.fetchChangelogMutex.Lock()
	ret, specificReturn := fake.fetchChangelogReturnsOnCall[len(fake.fetchChangelogArgsForCall)]
	fake.fetchChangelogArgsForCall = append(fake.fetchChangelogArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.FetchChangelogStub
	fakeReturns := fake.fetchChangelogReturns
	fake.recordInvocation("FetchChangelog", []interface{}{arg1, arg2, arg3})
	fake.fetchChangelogMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ReviewClient) FetchChangelogCallCount() int {
	fake.fetchChangelogMutex.RLock()
	defer fake.fetchChangelogMutex.RUnlock()
	return len(fake.fetchChangelogArgsForCall)
}

func (fake *ReviewClient) FetchChangelogCalls(stub func(context.Context, string, string) ([]byte, error)) {
	fake.fetchChangelogMutex.Lock()
	defer fake.fetchChangelogMutex.Unlock()
	fake.FetchChangelogStub = stub
}

func (fake *ReviewClient) FetchChangelogArgsForCall(i int) (context.Context, string, string) {
	fake.fetchChangelogMutex.RLock()
	defer fake.fetchChangelogMutex.RUnlock()
	argsForCall := fake.fetchChangelogArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *ReviewClient) FetchChangelogReturns(result1 []byte, result2 error) {
	fake.fetchChangelogMutex.Lock()
	defer fake.fetchChangelogMutex.Unlock()
	fake.FetchChangelogStub = nil
	fake.fetchChangelogReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *ReviewClient) FetchChangelogReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.fetchChangelogMutex.Lock()
	defer fake.fetchChangelogMutex.Unlock()
	fake.FetchChangelogStub = nil
	if fake.fetchChangelogReturnsOnCall == nil {
		fake.fetchChangelogReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.fetchChangelogReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *ReviewClient) ResolveTagCommit(arg1 context.Context, arg2 string, arg3 string, arg4 string) (string, error) {
	fake.resolveTagCommitMutex.Lock()
	ret, specificReturn := fake.resolveTagCommitReturnsOnCall[len(fake.resolveTagCommitArgsForCall)]
	fake.resolveTagCommitArgsForCall = append(fake.resolveTagCommitArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.ResolveTagCommitStub
	fakeReturns := fake.resolveTagCommitReturns
	fake.recordInvocation("ResolveTagCommit", []interface{}{arg1, arg2, arg3, arg4})
	fake.resolveTagCommitMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ReviewClient) ResolveTagCommitCallCount() int {
	fake.resolveTagCommitMutex.RLock()
	defer fake.resolveTagCommitMutex.RUnlock()
	return len(fake.resolveTagCommitArgsForCall)
}

func (fake *ReviewClient) ResolveTagCommitCalls(stub func(context.Context, string, string, string) (string, error)) {
	fake.resolveTagCommitMutex.Lock()
	defer fake.resolveTagCommitMutex.Unlock()
	fake.ResolveTagCommitStub = stub
}

func (fake *ReviewClient) ResolveTagCommitArgsForCall(i int) (context.Context, string, string, string) {
	fake.resolveTagCommitMutex.RLock()
	defer fake.resolveTagCommitMutex.RUnlock()
	argsForCall := fake.resolveTagCommitArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *ReviewClient) ResolveTagCommitReturns(result1 string, result2 error) {
	fake.resolveTagCommitMutex.Lock()
	defer fake.resolveTagCommitMutex.Unlock()
	fake.ResolveTagCommitStub = nil
	fake.resolveTagCommitReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *ReviewClient) ResolveTagCommitReturnsOnCall(i int, result1 string, result2 error) {
	fake.resolveTagCommitMutex.Lock()
	defer fake.resolveTagCommitMutex.Unlock()
	fake.ResolveTagCommitStub = nil
	if fake.resolveTagCommitReturnsOnCall == nil {
		fake.resolveTagCommitReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.resolveTagCommitReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *ReviewClient) TagExists(arg1 context.Context, arg2 string, arg3 string, arg4 string) (string, error) {
	fake.tagExistsMutex.Lock()
	ret, specificReturn := fake.tagExistsReturnsOnCall[len(fake.tagExistsArgsForCall)]
	fake.tagExistsArgsForCall = append(fake.tagExistsArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.TagExistsStub
	fakeReturns := fake.tagExistsReturns
	fake.recordInvocation("TagExists", []interface{}{arg1, arg2, arg3, arg4})
	fake.tagExistsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ReviewClient) TagExistsCallCount() int {
	fake.tagExistsMutex.RLock()
	defer fake.tagExistsMutex.RUnlock()
	return len(fake.tagExistsArgsForCall)
}

func (fake *ReviewClient) TagExistsCalls(stub func(context.Context, string, string, string) (string, error)) {
	fake.tagExistsMutex.Lock()
	defer fake.tagExistsMutex.Unlock()
	fake.TagExistsStub = stub
}

func (fake *ReviewClient) TagExistsArgsForCall(i int) (context.Context, string, string, string) {
	fake.tagExistsMutex.RLock()
	defer fake.tagExistsMutex.RUnlock()
	argsForCall := fake.tagExistsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *ReviewClient) TagExistsReturns(result1 string, result2 error) {
	fake.tagExistsMutex.Lock()
	defer fake.tagExistsMutex.Unlock()
	fake.TagExistsStub = nil
	fake.tagExistsReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *ReviewClient) TagExistsReturnsOnCall(i int, result1 string, result2 error) {
	fake.tagExistsMutex.Lock()
	defer fake.tagExistsMutex.Unlock()
	fake.TagExistsStub = nil
	if fake.tagExistsReturnsOnCall == nil {
		fake.tagExistsReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.tagExistsReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *ReviewClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ReviewClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ githubreview.Client = new(ReviewClient)
