DIRS += $(shell find */* -maxdepth 0 -name Makefile -exec dirname "{}" \;)

default: precommit

.PHONY: precommit
precommit:
	@for i in $(DIRS); do \
		echo "precommit $${i}"; \
		(cd $(CURDIR)/$$i && make precommit) || exit 1; \
	done

.PHONY: ensure
ensure:
	@for i in $(DIRS); do \
		echo "ensure $${i}"; \
		(cd $(CURDIR)/$$i && make ensure) || exit 1; \
	done

.PHONY: test
test:
	@for i in $(DIRS); do \
		echo "test $${i}"; \
		(cd $(CURDIR)/$$i && make test) || exit 1; \
	done

.PHONY: format
format:
	@for i in $(DIRS); do \
		echo "format $${i}"; \
		(cd $(CURDIR)/$$i && make format) || exit 1; \
	done

.PHONY: lint
lint:
	@for i in $(DIRS); do \
		echo "lint $${i}"; \
		(cd $(CURDIR)/$$i && make lint) || exit 1; \
	done

.PHONY: check
check:
	@for i in $(DIRS); do \
		echo "check $${i}"; \
		(cd $(CURDIR)/$$i && make check) || exit 1; \
	done

.PHONY: build
build:
	@for i in $(DIRS); do \
		echo "build $${i}"; \
		(cd $(CURDIR)/$$i && make build) || exit 1; \
	done

.PHONY: clean
clean:
	@for i in $(DIRS); do \
		echo "clean $${i}"; \
		(cd $(CURDIR)/$$i && make clean) || exit 1; \
	done

.PHONY: buca
buca:
	@for i in $(DIRS); do \
		echo "buca $${i}"; \
		(cd $(CURDIR)/$$i && make buca) || exit 1; \
	done

.PHONY: apply
apply:
	@for i in $(DIRS); do \
		echo "apply $${i}"; \
		(cd $(CURDIR)/$$i && make apply) || exit 1; \
	done

gomodtidy:
	find $$(pwd) -name go.mod -not -path "*/vendor/*" -exec dirname {} + \
		| sort -u \
		| xargs -I {} sh -c ' \
			echo "go mod tidy {}"; \
			(cd "{}" && go mod tidy && go run -mod=mod github.com/shoenig/go-modtool -w fmt go.mod) \
		'

.PHONY: fix
fix:
	@for dir in $$(find `pwd` -type d -name vendor -prune -o -name go.mod -exec dirname "{}" \; | grep -v '^$$'); do \
		cd $${dir}; \
		echo "fix $${dir}"; \
		go get \
		github.com/bborbe/kv@latest \
		github.com/bborbe/memorykv@latest \
		github.com/bborbe/badgerkv@latest \
		github.com/bborbe/boltkv@latest \
		github.com/go-git/go-git/v5@latest \
		github.com/containerd/containerd@latest \
		golang.org/x/crypto@latest \
		golang.org/x/net@latest; \
	done
