// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/maintainer/watcher/github-build/pkg"
)

type CommandPublisher struct {
	PublishCreateStub        func(context.Context, pkg.WatcherCreateTaskCommand) error
	publishCreateMutex       sync.RWMutex
	publishCreateArgsForCall []struct {
		arg1 context.Context
		arg2 pkg.WatcherCreateTaskCommand
	}
	publishCreateReturns struct {
		result1 error
	}
	publishCreateReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *CommandPublisher) PublishCreate(arg1 context.Context, arg2 pkg.WatcherCreateTaskCommand) error {
	fake.publishCreateMutex.Lock()
	ret, specificReturn := fake.publishCreateReturnsOnCall[len(fake.publishCreateArgsForCall)]
	fake.publishCreateArgsForCall = append(fake.publishCreateArgsForCall, struct {
		arg1 context.Context
		arg2 pkg.WatcherCreateTaskCommand
	}{arg1, arg2})
	stub := fake.PublishCreateStub
	fakeReturns := fake.publishCreateReturns
	fake.recordInvocation("PublishCreate", []interface{}{arg1, arg2})
	fake.publishCreateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *CommandPublisher) PublishCreateCallCount() int {
	fake.publishCreateMutex.RLock()
	defer fake.publishCreateMutex.RUnlock()
	return len(fake.publishCreateArgsForCall)
}

func (fake *CommandPublisher) PublishCreateCalls(stub func(context.Context, pkg.WatcherCreateTaskCommand) error) {
	fake.publishCreateMutex.Lock()
	defer fake.publishCreateMutex.Unlock()
	fake.PublishCreateStub = stub
}

func (fake *CommandPublisher) PublishCreateArgsForCall(i int) (context.Context, pkg.WatcherCreateTaskCommand) {
	fake.publishCreateMutex.RLock()
	defer fake.publishCreateMutex.RUnlock()
	argsForCall := fake.publishCreateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *CommandPublisher) PublishCreateReturns(result1 error) {
	fake.publishCreateMutex.Lock()
	defer fake.publishCreateMutex.Unlock()
	fake.PublishCreateStub = nil
	fake.publishCreateReturns = struct {
		result1 error
	}{result1}
}

func (fake *CommandPublisher) PublishCreateReturnsOnCall(i int, result1 error) {
	fake.publishCreateMutex.Lock()
	defer fake.publishCreateMutex.Unlock()
	fake.PublishCreateStub = nil
	if fake.publishCreateReturnsOnCall == nil {
		fake.publishCreateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.publishCreateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *CommandPublisher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *CommandPublisher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.CommandPublisher = new(CommandPublisher)
