// Code generated by counterfeiter. DO NOT EDIT.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/maintainer/watcher/github-build/pkg/maintenance"
)

type FileContentFetcher struct {
	GetFileContentStub        func(context.Context, string, string, string, string) ([]byte, error)
	getFileContentMutex       sync.RWMutex
	getFileContentArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 string
	}
	getFileContentReturns struct {
		result1 []byte
		result2 error
	}
	getFileContentReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FileContentFetcher) GetFileContent(arg1 context.Context, arg2 string, arg3 string, arg4 string, arg5 string) ([]byte, error) {
	fake.getFileContentMutex.Lock()
	ret, specificReturn := fake.getFileContentReturnsOnCall[len(fake.getFileContentArgsForCall)]
	fake.getFileContentArgsForCall = append(fake.getFileContentArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 string
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.GetFileContentStub
	fakeReturns := fake.getFileContentReturns
	fake.recordInvocation("GetFileContent", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.getFileContentMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FileContentFetcher) GetFileContentCallCount() int {
	fake.getFileContentMutex.RLock()
	defer fake.getFileContentMutex.RUnlock()
	return len(fake.getFileContentArgsForCall)
}

func (fake *FileContentFetcher) GetFileContentCalls(stub func(context.Context, string, string, string, string) ([]byte, error)) {
	fake.getFileContentMutex.Lock()
	defer fake.getFileContentMutex.Unlock()
	fake.GetFileContentStub = stub
}

func (fake *FileContentFetcher) GetFileContentArgsForCall(i int) (context.Context, string, string, string, string) {
	fake.getFileContentMutex.RLock()
	defer fake.getFileContentMutex.RUnlock()
	argsForCall := fake.getFileContentArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FileContentFetcher) GetFileContentReturns(result1 []byte, result2 error) {
	fake.getFileContentMutex.Lock()
	defer fake.getFileContentMutex.Unlock()
	fake.GetFileContentStub = nil
	fake.getFileContentReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FileContentFetcher) GetFileContentReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.getFileContentMutex.Lock()
	defer fake.getFileContentMutex.Unlock()
	fake.GetFileContentStub = nil
	if fake.getFileContentReturnsOnCall == nil {
		fake.getFileContentReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.getFileContentReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FileContentFetcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FileContentFetcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ maintenance.FileContentFetcher = new(FileContentFetcher)
