// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/maintainer/watcher/github-build/pkg"
)

type GitHubClient struct {
	GetDefaultBranchStub        func(context.Context, string, string) (string, error)
	getDefaultBranchMutex       sync.RWMutex
	getDefaultBranchArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	getDefaultBranchReturns struct {
		result1 string
		result2 error
	}
	getDefaultBranchReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	GetFileContentStub        func(context.Context, string, string, string, string) ([]byte, error)
	getFileContentMutex       sync.RWMutex
	getFileContentArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 string
	}
	getFileContentReturns struct {
		result1 []byte
		result2 error
	}
	getFileContentReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	GetWorkflowRunsStub        func(context.Context, string, string, string) ([]pkg.WorkflowRun, error)
	getWorkflowRunsMutex       sync.RWMutex
	getWorkflowRunsArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	getWorkflowRunsReturns struct {
		result1 []pkg.WorkflowRun
		result2 error
	}
	getWorkflowRunsReturnsOnCall map[int]struct {
		result1 []pkg.WorkflowRun
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *GitHubClient) GetDefaultBranch(arg1 context.Context, arg2 string, arg3 string) (string, error) {
	fake.getDefaultBranchMutex.Lock()
	ret, specificReturn := fake.getDefaultBranchReturnsOnCall[len(fake.getDefaultBranchArgsForCall)]
	fake.getDefaultBranchArgsForCall = append(fake.getDefaultBranchArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.GetDefaultBranchStub
	fakeReturns := fake.getDefaultBranchReturns
	fake.recordInvocation("GetDefaultBranch", []interface{}{arg1, arg2, arg3})
	fake.getDefaultBranchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitHubClient) GetDefaultBranchCallCount() int {
	fake.getDefaultBranchMutex.RLock()
	defer fake.getDefaultBranchMutex.RUnlock()
	return len(fake.getDefaultBranchArgsForCall)
}

func (fake *GitHubClient) GetDefaultBranchCalls(stub func(context.Context, string, string) (string, error)) {
	fake.getDefaultBranchMutex.Lock()
	defer fake.getDefaultBranchMutex.Unlock()
	fake.GetDefaultBranchStub = stub
}

func (fake *GitHubClient) GetDefaultBranchArgsForCall(i int) (context.Context, string, string) {
	fake.getDefaultBranchMutex.RLock()
	defer fake.getDefaultBranchMutex.RUnlock()
	argsForCall := fake.getDefaultBranchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *GitHubClient) GetDefaultBranchReturns(result1 string, result2 error) {
	fake.getDefaultBranchMutex.Lock()
	defer fake.getDefaultBranchMutex.Unlock()
	fake.GetDefaultBranchStub = nil
	fake.getDefaultBranchReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) GetDefaultBranchReturnsOnCall(i int, result1 string, result2 error) {
	fake.getDefaultBranchMutex.Lock()
	defer fake.getDefaultBranchMutex.Unlock()
	fake.GetDefaultBranchStub = nil
	if fake.getDefaultBranchReturnsOnCall == nil {
		fake.getDefaultBranchReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.getDefaultBranchReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) GetFileContent(arg1 context.Context, arg2 string, arg3 string, arg4 string, arg5 string) ([]byte, error) {
	fake.getFileContentMutex.Lock()
	ret, specificReturn := fake.getFileContentReturnsOnCall[len(fake.getFileContentArgsForCall)]
	fake.getFileContentArgsForCall = append(fake.getFileContentArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 string
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.GetFileContentStub
	fakeReturns := fake.getFileContentReturns
	fake.recordInvocation("GetFileContent", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.getFileContentMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitHubClient) GetFileContentCallCount() int {
	fake.getFileContentMutex.RLock()
	defer fake.getFileContentMutex.RUnlock()
	return len(fake.getFileContentArgsForCall)
}

func (fake *GitHubClient) GetFileContentCalls(stub func(context.Context, string, string, string, string) ([]byte, error)) {
	fake.getFileContentMutex.Lock()
	defer fake.getFileContentMutex.Unlock()
	fake.GetFileContentStub = stub
}

func (fake *GitHubClient) GetFileContentArgsForCall(i int) (context.Context, string, string, string, string) {
	fake.getFileContentMutex.RLock()
	defer fake.getFileContentMutex.RUnlock()
	argsForCall := fake.getFileContentArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *GitHubClient) GetFileContentReturns(result1 []byte, result2 error) {
	fake.getFileContentMutex.Lock()
	defer fake.getFileContentMutex.Unlock()
	fake.GetFileContentStub = nil
	fake.getFileContentReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) GetFileContentReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.getFileContentMutex.Lock()
	defer fake.getFileContentMutex.Unlock()
	fake.GetFileContentStub = nil
	if fake.getFileContentReturnsOnCall == nil {
		fake.getFileContentReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.getFileContentReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) GetWorkflowRuns(arg1 context.Context, arg2 string, arg3 string, arg4 string) ([]pkg.WorkflowRun, error) {
	fake.getWorkflowRunsMutex.Lock()
	ret, specificReturn := fake.getWorkflowRunsReturnsOnCall[len(fake.getWorkflowRunsArgsForCall)]
	fake.getWorkflowRunsArgsForCall = append(fake.getWorkflowRunsArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.GetWorkflowRunsStub
	fakeReturns := fake.getWorkflowRunsReturns
	fake.recordInvocation("GetWorkflowRuns", []interface{}{arg1, arg2, arg3, arg4})
	fake.getWorkflowRunsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitHubClient) GetWorkflowRunsCallCount() int {
	fake.getWorkflowRunsMutex.RLock()
	defer fake.getWorkflowRunsMutex.RUnlock()
	return len(fake.getWorkflowRunsArgsForCall)
}

func (fake *GitHubClient) GetWorkflowRunsCalls(stub func(context.Context, string, string, string) ([]pkg.WorkflowRun, error)) {
	fake.getWorkflowRunsMutex.Lock()
	defer fake.getWorkflowRunsMutex.Unlock()
	fake.GetWorkflowRunsStub = stub
}

func (fake *GitHubClient) GetWorkflowRunsArgsForCall(i int) (context.Context, string, string, string) {
	fake.getWorkflowRunsMutex.RLock()
	defer fake.getWorkflowRunsMutex.RUnlock()
	argsForCall := fake.getWorkflowRunsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *GitHubClient) GetWorkflowRunsReturns(result1 []pkg.WorkflowRun, result2 error) {
	fake.getWorkflowRunsMutex.Lock()
	defer fake.getWorkflowRunsMutex.Unlock()
	fake.GetWorkflowRunsStub = nil
	fake.getWorkflowRunsReturns = struct {
		result1 []pkg.WorkflowRun
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) GetWorkflowRunsReturnsOnCall(i int, result1 []pkg.WorkflowRun, result2 error) {
	fake.getWorkflowRunsMutex.Lock()
	defer fake.getWorkflowRunsMutex.Unlock()
	fake.GetWorkflowRunsStub = nil
	if fake.getWorkflowRunsReturnsOnCall == nil {
		fake.getWorkflowRunsReturnsOnCall = make(map[int]struct {
			result1 []pkg.WorkflowRun
			result2 error
		})
	}
	fake.getWorkflowRunsReturnsOnCall[i] = struct {
		result1 []pkg.WorkflowRun
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *GitHubClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.GitHubClient = new(GitHubClient)
