// Code generated by counterfeiter. DO NOT EDIT.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/maintainer/watcher/github-build/pkg/maintenance"
)

type MaintenanceLoader struct {
	LoadOverridesStub        func(context.Context, string, string, string) maintenance.GithubBuildConfig
	loadOverridesMutex       sync.RWMutex
	loadOverridesArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	loadOverridesReturns struct {
		result1 maintenance.GithubBuildConfig
	}
	loadOverridesReturnsOnCall map[int]struct {
		result1 maintenance.GithubBuildConfig
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *MaintenanceLoader) LoadOverrides(arg1 context.Context, arg2 string, arg3 string, arg4 string) maintenance.GithubBuildConfig {
	fake.loadOverridesMutex.Lock()
	ret, specificReturn := fake.loadOverridesReturnsOnCall[len(fake.loadOverridesArgsForCall)]
	fake.loadOverridesArgsForCall = append(fake.loadOverridesArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.LoadOverridesStub
	fakeReturns := fake.loadOverridesReturns
	fake.recordInvocation("LoadOverrides", []interface{}{arg1, arg2, arg3, arg4})
	fake.loadOverridesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *MaintenanceLoader) LoadOverridesCallCount() int {
	fake.loadOverridesMutex.RLock()
	defer fake.loadOverridesMutex.RUnlock()
	return len(fake.loadOverridesArgsForCall)
}

func (fake *MaintenanceLoader) LoadOverridesCalls(stub func(context.Context, string, string, string) maintenance.GithubBuildConfig) {
	fake.loadOverridesMutex.Lock()
	defer fake.loadOverridesMutex.Unlock()
	fake.LoadOverridesStub = stub
}

func (fake *MaintenanceLoader) LoadOverridesArgsForCall(i int) (context.Context, string, string, string) {
	fake.loadOverridesMutex.RLock()
	defer fake.loadOverridesMutex.RUnlock()
	argsForCall := fake.loadOverridesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *MaintenanceLoader) LoadOverridesReturns(result1 maintenance.GithubBuildConfig) {
	fake.loadOverridesMutex.Lock()
	defer fake.loadOverridesMutex.Unlock()
	fake.LoadOverridesStub = nil
	fake.loadOverridesReturns = struct {
		result1 maintenance.GithubBuildConfig
	}{result1}
}

func (fake *MaintenanceLoader) LoadOverridesReturnsOnCall(i int, result1 maintenance.GithubBuildConfig) {
	fake.loadOverridesMutex.Lock()
	defer fake.loadOverridesMutex.Unlock()
	fake.LoadOverridesStub = nil
	if fake.loadOverridesReturnsOnCall == nil {
		fake.loadOverridesReturnsOnCall = make(map[int]struct {
			result1 maintenance.GithubBuildConfig
		})
	}
	fake.loadOverridesReturnsOnCall[i] = struct {
		result1 maintenance.GithubBuildConfig
	}{result1}
}

func (fake *MaintenanceLoader) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *MaintenanceLoader) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ maintenance.Loader = new(MaintenanceLoader)
