// Code generated by counterfeiter. DO NOT EDIT.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
package mocks

import (
	"sync"

	"github.com/bborbe/maintainer/watcher/github-build/pkg"
)

type Metrics struct {
	IncPollCycleStub        func(string)
	incPollCycleMutex       sync.RWMutex
	incPollCycleArgsForCall []struct {
		arg1 string
	}
	IncPollErrorStub        func(string)
	incPollErrorMutex       sync.RWMutex
	incPollErrorArgsForCall []struct {
		arg1 string
	}
	IncReposCheckedStub        func()
	incReposCheckedMutex       sync.RWMutex
	incReposCheckedArgsForCall []struct {
	}
	IncStateTransitionStub        func(string)
	incStateTransitionMutex       sync.RWMutex
	incStateTransitionArgsForCall []struct {
		arg1 string
	}
	IncTaskPublishedStub        func()
	incTaskPublishedMutex       sync.RWMutex
	incTaskPublishedArgsForCall []struct {
	}
	SetCurrentRedReposStub        func(float64)
	setCurrentRedReposMutex       sync.RWMutex
	setCurrentRedReposArgsForCall []struct {
		arg1 float64
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Metrics) IncPollCycle(arg1 string) {
	fake.incPollCycleMutex.Lock()
	fake.incPollCycleArgsForCall = append(fake.incPollCycleArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IncPollCycleStub
	fake.recordInvocation("IncPollCycle", []interface{}{arg1})
	fake.incPollCycleMutex.Unlock()
	if stub != nil {
		fake.IncPollCycleStub(arg1)
	}
}

func (fake *Metrics) IncPollCycleCallCount() int {
	fake.incPollCycleMutex.RLock()
	defer fake.incPollCycleMutex.RUnlock()
	return len(fake.incPollCycleArgsForCall)
}

func (fake *Metrics) IncPollCycleCalls(stub func(string)) {
	fake.incPollCycleMutex.Lock()
	defer fake.incPollCycleMutex.Unlock()
	fake.IncPollCycleStub = stub
}

func (fake *Metrics) IncPollCycleArgsForCall(i int) string {
	fake.incPollCycleMutex.RLock()
	defer fake.incPollCycleMutex.RUnlock()
	argsForCall := fake.incPollCycleArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Metrics) IncPollError(arg1 string) {
	fake.incPollErrorMutex.Lock()
	fake.incPollErrorArgsForCall = append(fake.incPollErrorArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IncPollErrorStub
	fake.recordInvocation("IncPollError", []interface{}{arg1})
	fake.incPollErrorMutex.Unlock()
	if stub != nil {
		fake.IncPollErrorStub(arg1)
	}
}

func (fake *Metrics) IncPollErrorCallCount() int {
	fake.incPollErrorMutex.RLock()
	defer fake.incPollErrorMutex.RUnlock()
	return len(fake.incPollErrorArgsForCall)
}

func (fake *Metrics) IncPollErrorCalls(stub func(string)) {
	fake.incPollErrorMutex.Lock()
	defer fake.incPollErrorMutex.Unlock()
	fake.IncPollErrorStub = stub
}

func (fake *Metrics) IncPollErrorArgsForCall(i int) string {
	fake.incPollErrorMutex.RLock()
	defer fake.incPollErrorMutex.RUnlock()
	argsForCall := fake.incPollErrorArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Metrics) IncReposChecked() {
	fake.incReposCheckedMutex.Lock()
	fake.incReposCheckedArgsForCall = append(fake.incReposCheckedArgsForCall, struct {
	}{})
	stub := fake.IncReposCheckedStub
	fake.recordInvocation("IncReposChecked", []interface{}{})
	fake.incReposCheckedMutex.Unlock()
	if stub != nil {
		fake.IncReposCheckedStub()
	}
}

func (fake *Metrics) IncReposCheckedCallCount() int {
	fake.incReposCheckedMutex.RLock()
	defer fake.incReposCheckedMutex.RUnlock()
	return len(fake.incReposCheckedArgsForCall)
}

func (fake *Metrics) IncReposCheckedCalls(stub func()) {
	fake.incReposCheckedMutex.Lock()
	defer fake.incReposCheckedMutex.Unlock()
	fake.IncReposCheckedStub = stub
}

func (fake *Metrics) IncStateTransition(arg1 string) {
	fake.incStateTransitionMutex.Lock()
	fake.incStateTransitionArgsForCall = append(fake.incStateTransitionArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IncStateTransitionStub
	fake.recordInvocation("IncStateTransition", []interface{}{arg1})
	fake.incStateTransitionMutex.Unlock()
	if stub != nil {
		fake.IncStateTransitionStub(arg1)
	}
}

func (fake *Metrics) IncStateTransitionCallCount() int {
	fake.incStateTransitionMutex.RLock()
	defer fake.incStateTransitionMutex.RUnlock()
	return len(fake.incStateTransitionArgsForCall)
}

func (fake *Metrics) IncStateTransitionCalls(stub func(string)) {
	fake.incStateTransitionMutex.Lock()
	defer fake.incStateTransitionMutex.Unlock()
	fake.IncStateTransitionStub = stub
}

func (fake *Metrics) IncStateTransitionArgsForCall(i int) string {
	fake.incStateTransitionMutex.RLock()
	defer fake.incStateTransitionMutex.RUnlock()
	argsForCall := fake.incStateTransitionArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Metrics) IncTaskPublished() {
	fake.incTaskPublishedMutex.Lock()
	fake.incTaskPublishedArgsForCall = append(fake.incTaskPublishedArgsForCall, struct {
	}{})
	stub := fake.IncTaskPublishedStub
	fake.recordInvocation("IncTaskPublished", []interface{}{})
	fake.incTaskPublishedMutex.Unlock()
	if stub != nil {
		fake.IncTaskPublishedStub()
	}
}

func (fake *Metrics) IncTaskPublishedCallCount() int {
	fake.incTaskPublishedMutex.RLock()
	defer fake.incTaskPublishedMutex.RUnlock()
	return len(fake.incTaskPublishedArgsForCall)
}

func (fake *Metrics) IncTaskPublishedCalls(stub func()) {
	fake.incTaskPublishedMutex.Lock()
	defer fake.incTaskPublishedMutex.Unlock()
	fake.IncTaskPublishedStub = stub
}

func (fake *Metrics) SetCurrentRedRepos(arg1 float64) {
	fake.setCurrentRedReposMutex.Lock()
	fake.setCurrentRedReposArgsForCall = append(fake.setCurrentRedReposArgsForCall, struct {
		arg1 float64
	}{arg1})
	stub := fake.SetCurrentRedReposStub
	fake.recordInvocation("SetCurrentRedRepos", []interface{}{arg1})
	fake.setCurrentRedReposMutex.Unlock()
	if stub != nil {
		fake.SetCurrentRedReposStub(arg1)
	}
}

func (fake *Metrics) SetCurrentRedReposCallCount() int {
	fake.setCurrentRedReposMutex.RLock()
	defer fake.setCurrentRedReposMutex.RUnlock()
	return len(fake.setCurrentRedReposArgsForCall)
}

func (fake *Metrics) SetCurrentRedReposCalls(stub func(float64)) {
	fake.setCurrentRedReposMutex.Lock()
	defer fake.setCurrentRedReposMutex.Unlock()
	fake.SetCurrentRedReposStub = stub
}

func (fake *Metrics) SetCurrentRedReposArgsForCall(i int) float64 {
	fake.setCurrentRedReposMutex.RLock()
	defer fake.setCurrentRedReposMutex.RUnlock()
	argsForCall := fake.setCurrentRedReposArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Metrics) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Metrics) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.Metrics = new(Metrics)
