// Code generated by counterfeiter. DO NOT EDIT.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
package mocks

import (
	"sync"

	"github.com/bborbe/maintainer/watcher/github-release/pkg/filter"
)

type CursorReader struct {
	LastSeenSHAStub        func(string) string
	lastSeenSHAMutex       sync.RWMutex
	lastSeenSHAArgsForCall []struct {
		arg1 string
	}
	lastSeenSHAReturns struct {
		result1 string
	}
	lastSeenSHAReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *CursorReader) LastSeenSHA(arg1 string) string {
	fake.lastSeenSHAMutex.Lock()
	ret, specificReturn := fake.lastSeenSHAReturnsOnCall[len(fake.lastSeenSHAArgsForCall)]
	fake.lastSeenSHAArgsForCall = append(fake.lastSeenSHAArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.LastSeenSHAStub
	fakeReturns := fake.lastSeenSHAReturns
	fake.recordInvocation("LastSeenSHA", []interface{}{arg1})
	fake.lastSeenSHAMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *CursorReader) LastSeenSHACallCount() int {
	fake.lastSeenSHAMutex.RLock()
	defer fake.lastSeenSHAMutex.RUnlock()
	return len(fake.lastSeenSHAArgsForCall)
}

func (fake *CursorReader) LastSeenSHACalls(stub func(string) string) {
	fake.lastSeenSHAMutex.Lock()
	defer fake.lastSeenSHAMutex.Unlock()
	fake.LastSeenSHAStub = stub
}

func (fake *CursorReader) LastSeenSHAArgsForCall(i int) string {
	fake.lastSeenSHAMutex.RLock()
	defer fake.lastSeenSHAMutex.RUnlock()
	argsForCall := fake.lastSeenSHAArgsForCall[i]
	return argsForCall.arg1
}

func (fake *CursorReader) LastSeenSHAReturns(result1 string) {
	fake.lastSeenSHAMutex.Lock()
	defer fake.lastSeenSHAMutex.Unlock()
	fake.LastSeenSHAStub = nil
	fake.lastSeenSHAReturns = struct {
		result1 string
	}{result1}
}

func (fake *CursorReader) LastSeenSHAReturnsOnCall(i int, result1 string) {
	fake.lastSeenSHAMutex.Lock()
	defer fake.lastSeenSHAMutex.Unlock()
	fake.LastSeenSHAStub = nil
	if fake.lastSeenSHAReturnsOnCall == nil {
		fake.lastSeenSHAReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.lastSeenSHAReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *CursorReader) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *CursorReader) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ filter.CursorReader = new(CursorReader)
