// Code generated by counterfeiter. DO NOT EDIT.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/maintainer/watcher/github-release/pkg"
)

type GitHubClient struct {
	GetChangelogContentStub        func(context.Context, pkg.Repo) ([]byte, error)
	getChangelogContentMutex       sync.RWMutex
	getChangelogContentArgsForCall []struct {
		arg1 context.Context
		arg2 pkg.Repo
	}
	getChangelogContentReturns struct {
		result1 []byte
		result2 error
	}
	getChangelogContentReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	GetMaintainerConfigStub        func(context.Context, pkg.Repo) (pkg.MaintainerConfig, error)
	getMaintainerConfigMutex       sync.RWMutex
	getMaintainerConfigArgsForCall []struct {
		arg1 context.Context
		arg2 pkg.Repo
	}
	getMaintainerConfigReturns struct {
		result1 pkg.MaintainerConfig
		result2 error
	}
	getMaintainerConfigReturnsOnCall map[int]struct {
		result1 pkg.MaintainerConfig
		result2 error
	}
	GetMasterSHAStub        func(context.Context, pkg.Repo) (string, error)
	getMasterSHAMutex       sync.RWMutex
	getMasterSHAArgsForCall []struct {
		arg1 context.Context
		arg2 pkg.Repo
	}
	getMasterSHAReturns struct {
		result1 string
		result2 error
	}
	getMasterSHAReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	ListReposStub        func(context.Context, string) ([]pkg.Repo, error)
	listReposMutex       sync.RWMutex
	listReposArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	listReposReturns struct {
		result1 []pkg.Repo
		result2 error
	}
	listReposReturnsOnCall map[int]struct {
		result1 []pkg.Repo
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *GitHubClient) GetChangelogContent(arg1 context.Context, arg2 pkg.Repo) ([]byte, error) {
	fake.getChangelogContentMutex.Lock()
	ret, specificReturn := fake.getChangelogContentReturnsOnCall[len(fake.getChangelogContentArgsForCall)]
	fake.getChangelogContentArgsForCall = append(fake.getChangelogContentArgsForCall, struct {
		arg1 context.Context
		arg2 pkg.Repo
	}{arg1, arg2})
	stub := fake.GetChangelogContentStub
	fakeReturns := fake.getChangelogContentReturns
	fake.recordInvocation("GetChangelogContent", []interface{}{arg1, arg2})
	fake.getChangelogContentMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitHubClient) GetChangelogContentCallCount() int {
	fake.getChangelogContentMutex.RLock()
	defer fake.getChangelogContentMutex.RUnlock()
	return len(fake.getChangelogContentArgsForCall)
}

func (fake *GitHubClient) GetChangelogContentCalls(stub func(context.Context, pkg.Repo) ([]byte, error)) {
	fake.getChangelogContentMutex.Lock()
	defer fake.getChangelogContentMutex.Unlock()
	fake.GetChangelogContentStub = stub
}

func (fake *GitHubClient) GetChangelogContentArgsForCall(i int) (context.Context, pkg.Repo) {
	fake.getChangelogContentMutex.RLock()
	defer fake.getChangelogContentMutex.RUnlock()
	argsForCall := fake.getChangelogContentArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *GitHubClient) GetChangelogContentReturns(result1 []byte, result2 error) {
	fake.getChangelogContentMutex.Lock()
	defer fake.getChangelogContentMutex.Unlock()
	fake.GetChangelogContentStub = nil
	fake.getChangelogContentReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) GetChangelogContentReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.getChangelogContentMutex.Lock()
	defer fake.getChangelogContentMutex.Unlock()
	fake.GetChangelogContentStub = nil
	if fake.getChangelogContentReturnsOnCall == nil {
		fake.getChangelogContentReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.getChangelogContentReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) GetMaintainerConfig(arg1 context.Context, arg2 pkg.Repo) (pkg.MaintainerConfig, error) {
	fake.getMaintainerConfigMutex.Lock()
	ret, specificReturn := fake.getMaintainerConfigReturnsOnCall[len(fake.getMaintainerConfigArgsForCall)]
	fake.getMaintainerConfigArgsForCall = append(fake.getMaintainerConfigArgsForCall, struct {
		arg1 context.Context
		arg2 pkg.Repo
	}{arg1, arg2})
	stub := fake.GetMaintainerConfigStub
	fakeReturns := fake.getMaintainerConfigReturns
	fake.recordInvocation("GetMaintainerConfig", []interface{}{arg1, arg2})
	fake.getMaintainerConfigMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitHubClient) GetMaintainerConfigCallCount() int {
	fake.getMaintainerConfigMutex.RLock()
	defer fake.getMaintainerConfigMutex.RUnlock()
	return len(fake.getMaintainerConfigArgsForCall)
}

func (fake *GitHubClient) GetMaintainerConfigCalls(stub func(context.Context, pkg.Repo) (pkg.MaintainerConfig, error)) {
	fake.getMaintainerConfigMutex.Lock()
	defer fake.getMaintainerConfigMutex.Unlock()
	fake.GetMaintainerConfigStub = stub
}

func (fake *GitHubClient) GetMaintainerConfigArgsForCall(i int) (context.Context, pkg.Repo) {
	fake.getMaintainerConfigMutex.RLock()
	defer fake.getMaintainerConfigMutex.RUnlock()
	argsForCall := fake.getMaintainerConfigArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *GitHubClient) GetMaintainerConfigReturns(result1 pkg.MaintainerConfig, result2 error) {
	fake.getMaintainerConfigMutex.Lock()
	defer fake.getMaintainerConfigMutex.Unlock()
	fake.GetMaintainerConfigStub = nil
	fake.getMaintainerConfigReturns = struct {
		result1 pkg.MaintainerConfig
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) GetMaintainerConfigReturnsOnCall(i int, result1 pkg.MaintainerConfig, result2 error) {
	fake.getMaintainerConfigMutex.Lock()
	defer fake.getMaintainerConfigMutex.Unlock()
	fake.GetMaintainerConfigStub = nil
	if fake.getMaintainerConfigReturnsOnCall == nil {
		fake.getMaintainerConfigReturnsOnCall = make(map[int]struct {
			result1 pkg.MaintainerConfig
			result2 error
		})
	}
	fake.getMaintainerConfigReturnsOnCall[i] = struct {
		result1 pkg.MaintainerConfig
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) GetMasterSHA(arg1 context.Context, arg2 pkg.Repo) (string, error) {
	fake.getMasterSHAMutex.Lock()
	ret, specificReturn := fake.getMasterSHAReturnsOnCall[len(fake.getMasterSHAArgsForCall)]
	fake.getMasterSHAArgsForCall = append(fake.getMasterSHAArgsForCall, struct {
		arg1 context.Context
		arg2 pkg.Repo
	}{arg1, arg2})
	stub := fake.GetMasterSHAStub
	fakeReturns := fake.getMasterSHAReturns
	fake.recordInvocation("GetMasterSHA", []interface{}{arg1, arg2})
	fake.getMasterSHAMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitHubClient) GetMasterSHACallCount() int {
	fake.getMasterSHAMutex.RLock()
	defer fake.getMasterSHAMutex.RUnlock()
	return len(fake.getMasterSHAArgsForCall)
}

func (fake *GitHubClient) GetMasterSHACalls(stub func(context.Context, pkg.Repo) (string, error)) {
	fake.getMasterSHAMutex.Lock()
	defer fake.getMasterSHAMutex.Unlock()
	fake.GetMasterSHAStub = stub
}

func (fake *GitHubClient) GetMasterSHAArgsForCall(i int) (context.Context, pkg.Repo) {
	fake.getMasterSHAMutex.RLock()
	defer fake.getMasterSHAMutex.RUnlock()
	argsForCall := fake.getMasterSHAArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *GitHubClient) GetMasterSHAReturns(result1 string, result2 error) {
	fake.getMasterSHAMutex.Lock()
	defer fake.getMasterSHAMutex.Unlock()
	fake.GetMasterSHAStub = nil
	fake.getMasterSHAReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) GetMasterSHAReturnsOnCall(i int, result1 string, result2 error) {
	fake.getMasterSHAMutex.Lock()
	defer fake.getMasterSHAMutex.Unlock()
	fake.GetMasterSHAStub = nil
	if fake.getMasterSHAReturnsOnCall == nil {
		fake.getMasterSHAReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.getMasterSHAReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) ListRepos(arg1 context.Context, arg2 string) ([]pkg.Repo, error) {
	fake.listReposMutex.Lock()
	ret, specificReturn := fake.listReposReturnsOnCall[len(fake.listReposArgsForCall)]
	fake.listReposArgsForCall = append(fake.listReposArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ListReposStub
	fakeReturns := fake.listReposReturns
	fake.recordInvocation("ListRepos", []interface{}{arg1, arg2})
	fake.listReposMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitHubClient) ListReposCallCount() int {
	fake.listReposMutex.RLock()
	defer fake.listReposMutex.RUnlock()
	return len(fake.listReposArgsForCall)
}

func (fake *GitHubClient) ListReposCalls(stub func(context.Context, string) ([]pkg.Repo, error)) {
	fake.listReposMutex.Lock()
	defer fake.listReposMutex.Unlock()
	fake.ListReposStub = stub
}

func (fake *GitHubClient) ListReposArgsForCall(i int) (context.Context, string) {
	fake.listReposMutex.RLock()
	defer fake.listReposMutex.RUnlock()
	argsForCall := fake.listReposArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *GitHubClient) ListReposReturns(result1 []pkg.Repo, result2 error) {
	fake.listReposMutex.Lock()
	defer fake.listReposMutex.Unlock()
	fake.ListReposStub = nil
	fake.listReposReturns = struct {
		result1 []pkg.Repo
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) ListReposReturnsOnCall(i int, result1 []pkg.Repo, result2 error) {
	fake.listReposMutex.Lock()
	defer fake.listReposMutex.Unlock()
	fake.ListReposStub = nil
	if fake.listReposReturnsOnCall == nil {
		fake.listReposReturnsOnCall = make(map[int]struct {
			result1 []pkg.Repo
			result2 error
		})
	}
	fake.listReposReturnsOnCall[i] = struct {
		result1 []pkg.Repo
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *GitHubClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.GitHubClient = new(GitHubClient)
