// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/bborbe/maintainer/watcher/github-release/pkg"
)

type Metrics struct {
	IncFilterSkippedStub        func(string)
	incFilterSkippedMutex       sync.RWMutex
	incFilterSkippedArgsForCall []struct {
		arg1 string
	}
	IncPollCycleStub        func(string)
	incPollCycleMutex       sync.RWMutex
	incPollCycleArgsForCall []struct {
		arg1 string
	}
	IncPublishedStub        func(string)
	incPublishedMutex       sync.RWMutex
	incPublishedArgsForCall []struct {
		arg1 string
	}
	IncReposScannedStub        func(int)
	incReposScannedMutex       sync.RWMutex
	incReposScannedArgsForCall []struct {
		arg1 int
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Metrics) IncFilterSkipped(arg1 string) {
	fake.incFilterSkippedMutex.Lock()
	fake.incFilterSkippedArgsForCall = append(fake.incFilterSkippedArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IncFilterSkippedStub
	fake.recordInvocation("IncFilterSkipped", []interface{}{arg1})
	fake.incFilterSkippedMutex.Unlock()
	if stub != nil {
		fake.IncFilterSkippedStub(arg1)
	}
}

func (fake *Metrics) IncFilterSkippedCallCount() int {
	fake.incFilterSkippedMutex.RLock()
	defer fake.incFilterSkippedMutex.RUnlock()
	return len(fake.incFilterSkippedArgsForCall)
}

func (fake *Metrics) IncFilterSkippedCalls(stub func(string)) {
	fake.incFilterSkippedMutex.Lock()
	defer fake.incFilterSkippedMutex.Unlock()
	fake.IncFilterSkippedStub = stub
}

func (fake *Metrics) IncFilterSkippedArgsForCall(i int) string {
	fake.incFilterSkippedMutex.RLock()
	defer fake.incFilterSkippedMutex.RUnlock()
	argsForCall := fake.incFilterSkippedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Metrics) IncPollCycle(arg1 string) {
	fake.incPollCycleMutex.Lock()
	fake.incPollCycleArgsForCall = append(fake.incPollCycleArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IncPollCycleStub
	fake.recordInvocation("IncPollCycle", []interface{}{arg1})
	fake.incPollCycleMutex.Unlock()
	if stub != nil {
		fake.IncPollCycleStub(arg1)
	}
}

func (fake *Metrics) IncPollCycleCallCount() int {
	fake.incPollCycleMutex.RLock()
	defer fake.incPollCycleMutex.RUnlock()
	return len(fake.incPollCycleArgsForCall)
}

func (fake *Metrics) IncPollCycleCalls(stub func(string)) {
	fake.incPollCycleMutex.Lock()
	defer fake.incPollCycleMutex.Unlock()
	fake.IncPollCycleStub = stub
}

func (fake *Metrics) IncPollCycleArgsForCall(i int) string {
	fake.incPollCycleMutex.RLock()
	defer fake.incPollCycleMutex.RUnlock()
	argsForCall := fake.incPollCycleArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Metrics) IncPublished(arg1 string) {
	fake.incPublishedMutex.Lock()
	fake.incPublishedArgsForCall = append(fake.incPublishedArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IncPublishedStub
	fake.recordInvocation("IncPublished", []interface{}{arg1})
	fake.incPublishedMutex.Unlock()
	if stub != nil {
		fake.IncPublishedStub(arg1)
	}
}

func (fake *Metrics) IncPublishedCallCount() int {
	fake.incPublishedMutex.RLock()
	defer fake.incPublishedMutex.RUnlock()
	return len(fake.incPublishedArgsForCall)
}

func (fake *Metrics) IncPublishedCalls(stub func(string)) {
	fake.incPublishedMutex.Lock()
	defer fake.incPublishedMutex.Unlock()
	fake.IncPublishedStub = stub
}

func (fake *Metrics) IncPublishedArgsForCall(i int) string {
	fake.incPublishedMutex.RLock()
	defer fake.incPublishedMutex.RUnlock()
	argsForCall := fake.incPublishedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Metrics) IncReposScanned(arg1 int) {
	fake.incReposScannedMutex.Lock()
	fake.incReposScannedArgsForCall = append(fake.incReposScannedArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.IncReposScannedStub
	fake.recordInvocation("IncReposScanned", []interface{}{arg1})
	fake.incReposScannedMutex.Unlock()
	if stub != nil {
		fake.IncReposScannedStub(arg1)
	}
}

func (fake *Metrics) IncReposScannedCallCount() int {
	fake.incReposScannedMutex.RLock()
	defer fake.incReposScannedMutex.RUnlock()
	return len(fake.incReposScannedArgsForCall)
}

func (fake *Metrics) IncReposScannedCalls(stub func(int)) {
	fake.incReposScannedMutex.Lock()
	defer fake.incReposScannedMutex.Unlock()
	fake.IncReposScannedStub = stub
}

func (fake *Metrics) IncReposScannedArgsForCall(i int) int {
	fake.incReposScannedMutex.RLock()
	defer fake.incReposScannedMutex.RUnlock()
	argsForCall := fake.incReposScannedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Metrics) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Metrics) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.Metrics = new(Metrics)
