// Code generated by counterfeiter. DO NOT EDIT.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/maintainer/watcher/github-release/pkg"
)

type TaskPublisher struct {
	PublishCreateStub        func(context.Context, pkg.Release) bool
	publishCreateMutex       sync.RWMutex
	publishCreateArgsForCall []struct {
		arg1 context.Context
		arg2 pkg.Release
	}
	publishCreateReturns struct {
		result1 bool
	}
	publishCreateReturnsOnCall map[int]struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *TaskPublisher) PublishCreate(arg1 context.Context, arg2 pkg.Release) bool {
	fake.publishCreateMutex.Lock()
	ret, specificReturn := fake.publishCreateReturnsOnCall[len(fake.publishCreateArgsForCall)]
	fake.publishCreateArgsForCall = append(fake.publishCreateArgsForCall, struct {
		arg1 context.Context
		arg2 pkg.Release
	}{arg1, arg2})
	stub := fake.PublishCreateStub
	fakeReturns := fake.publishCreateReturns
	fake.recordInvocation("PublishCreate", []interface{}{arg1, arg2})
	fake.publishCreateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *TaskPublisher) PublishCreateCallCount() int {
	fake.publishCreateMutex.RLock()
	defer fake.publishCreateMutex.RUnlock()
	return len(fake.publishCreateArgsForCall)
}

func (fake *TaskPublisher) PublishCreateCalls(stub func(context.Context, pkg.Release) bool) {
	fake.publishCreateMutex.Lock()
	defer fake.publishCreateMutex.Unlock()
	fake.PublishCreateStub = stub
}

func (fake *TaskPublisher) PublishCreateArgsForCall(i int) (context.Context, pkg.Release) {
	fake.publishCreateMutex.RLock()
	defer fake.publishCreateMutex.RUnlock()
	argsForCall := fake.publishCreateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *TaskPublisher) PublishCreateReturns(result1 bool) {
	fake.publishCreateMutex.Lock()
	defer fake.publishCreateMutex.Unlock()
	fake.PublishCreateStub = nil
	fake.publishCreateReturns = struct {
		result1 bool
	}{result1}
}

func (fake *TaskPublisher) PublishCreateReturnsOnCall(i int, result1 bool) {
	fake.publishCreateMutex.Lock()
	defer fake.publishCreateMutex.Unlock()
	fake.PublishCreateStub = nil
	if fake.publishCreateReturnsOnCall == nil {
		fake.publishCreateReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.publishCreateReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *TaskPublisher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *TaskPublisher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.TaskPublisher = new(TaskPublisher)
