apiVersion: v1
kind: Service
metadata:
  name: maintainer-watcher-github-release
  namespace: '{{ "NAMESPACE" | env }}'
  annotations:
    admin/port: '9090'
    admin/path: ''
spec:
  clusterIP: None
  selector:
    app: maintainer-watcher-github-release
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP
