apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: maintainer-watcher-github-release
  namespace: '{{ "NAMESPACE" | env }}'
data:
  PEM_KEY: '{{ "WATCHER_GITHUB_RELEASE_PEM_KEY" | env | teamvaultFileBase64 }}'
