apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: maintainer-agent-github-releaser
  namespace: '{{ "NAMESPACE" | env }}'
data:
  SENTRY_DSN: '{{ "SENTRY_DSN_KEY" | env | teamvaultUrl | base64 }}'
  ANTHROPIC_AUTH_TOKEN: '{{ "MOPmQL" | teamvaultPassword | base64 }}'
  PEM_KEY: '{{ "AGENT_GITHUB_RELEASER_PEM_KEY" | env | teamvaultFileBase64 }}'
