apiVersion: v1
kind: ResourceQuota
metadata:
  name: maintainer-agent-github-releaser
  namespace: dev
spec:
  hard:
    pods: "3"
  scopeSelector:
    matchExpressions:
      - scopeName: PriorityClass
        operator: In
        values: ["maintainer-agent-github-releaser"]
