apiVersion: v1
kind: ResourceQuota
metadata:
  name: maintainer-agent-github-releaser
  namespace: prod
spec:
  hard:
    pods: "1"
  scopeSelector:
    matchExpressions:
      - scopeName: PriorityClass
        operator: In
        values: ["maintainer-agent-github-releaser"]
