apiVersion: v1
kind: Service
metadata:
  name: github-pr-watcher
  namespace: '{{ "NAMESPACE" | env }}'
spec:
  clusterIP: None
  selector:
    app: github-pr-watcher
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP
