apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: github-pr-watcher
  namespace: '{{ "NAMESPACE" | env }}'
data:
  GH_TOKEN: '{{ "GH_PR_WATCHER_TOKEN_KEY" | env | teamvaultPassword | base64 }}'
